name: flutter_counter_shooter
description: Typical flutter counter demo project with an ability to shoot
publish_to: 'none'
version: 1.0.0+1

environment:
  flutter: ">=3.38.5"
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  audioplayers: ^6.5.1
  cloud_firestore: ^6.1.1
  collection: ^1.17.0
  firebase_analytics: ^12.1.0
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  google_fonts: ^6.3.3
  intl: ^0.20.2
  json_annotation: ^4.5.0
  meta: ^1.7.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.2.0
  melos: ^7.3.0
  test: ^1.24.1

flutter_intl:
  enabled: false # Required. Must be set to true to activate the plugin. Default: false
  class_name: AppLocalizations # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/google_fonts/
    - assets/images/
    - assets/sounds/

melos:
  scripts:
    generate:
      description: "Generate sources and format"
      run: |
        dart run melos exec --concurrency=1 --\
          dart pub run build_runner build --delete-conflicting-outputs && \
          dart run melos run format

    analyze:
      description: "Analyze"
      run: |
        dart run melos exec --concurrency=1 --\
          flutter analyze

    check:
      description: "Check format, analyze and test"
      run: |
        dart run melos exec --concurrency=1 --\
          dart run melos run format:check && \
          dart run melos run analyze && \
          dart run melos run test && \
          dart run melos run coverage:check

    coverage:
      description: "Show coverage in browser"
      run: |
        dart run melos run coverage:filter && \
        dart run melos run coverage:html && \
        open coverage/html/index.html

    coverage:check:
      description: "Check coverage"
      packageFilters:
        dirExists:
          - test
      run: |
        dart run melos exec --concurrency=1 --\
          dart pub global activate check_coverage && \
          cat coverage/lcov.info | check_coverage 75

    coverage:filter:
      description: "Filter coverage"
      run: |
        mv -f coverage/lcov.info coverage/lcov-all.info && \
        lcov --ignore-errors unused \
          --remove coverage/lcov-all.info \
          '*.g.dart' '*.freezed.dart' \
          -o coverage/lcov.info && \
        rm -f coverage/lcov-all.info

    coverage:html:
      description: "Generate html"
      run: |
        genhtml coverage/lcov.info -o coverage/html

    fix:
      description: "Dart fix"
      run: |
        dart run melos exec --concurrency=1 --\
          dart fix --apply

    format:
      description: "Format"
      run: |
        dart run melos exec --\
          dart format .

    format:check:
      description: "Check format"
      run: |
        dart run melos exec --concurrency=1 --\
          dart format --set-exit-if-changed .

    test:
      description: "Test"
      packageFilters:
        dirExists:
          - test
      run: |
        dart run melos exec --concurrency=1 --\
          flutter test --coverage -j 1 .

    upgrade:
      description: "Upgrade"
      run: |
        dart run melos exec --concurrency=1 --\
          flutter pub upgrade --major-versions

    deploy:
      description: "Deploy"
      run: |
        dart run melos run build && \
        pushd build/web && \
        firebase deploy  && \
        popd

    deploy:gh:
      description: "Build for GitHub Pages"
      run: |
        rm -rf build && \
        flutter build web --wasm -O4 --base-href "/flutter_counter_demo_shooter/"

    build:
      description: "Build"
      run: |
        rm -rf build && \
        flutter build web --wasm -O4
